### ISSUE TITLE
Grayscale is crashing for only iOS 17.4

### ISSUE THREAD

**Issue by JDWaghela** [iyegoroff/react-native-color-matrix-image-filters#126]
"platform" : "iOS"
"react-native": "0.72.4",
"react-native-color-matrix-image-filters": "^6.0.7",
"architecture" : "old"
Tested iOS Version : 17.4 (Simulator)
XCode Version : 15.3

Crash log : [Crash Log.txt](https://github.com/iyegoroff/react-native-color-matrix-image-filters/files/14521058/Crash.Log.txt)

To Reproduce Steps just use Grayscale component of library to wrap image / fastimage
`<Grayscale amount={1} style={{opacity: 0.7}}> <FastImage {...props} /> </Grayscale>`

iOS 17.4 is only crashing, all old versions are not crashing.

**Comment by subramanian-elavathur** [comment]
We are seeing the same issue on iOS version `17.4`

### Details

```json
platform : iOS
react-native: 0.71.11
react-native-color-matrix-image-filters: 6.0.7
architecture: old
iosVersion: 17.4 (simulator)
```

### Code to Reproduce

```typescript
import React, {useState} from 'react';
import {Image, Text, TouchableOpacity, View} from 'react-native';
import {Grayscale} from 'react-native-color-matrix-image-filters';
import {SafeAreaView} from 'react-native-safe-area-context';

export function ReproduceGreyscaleIssue() {
  const [showGreyScaleImage, setShowGreyScaleImage] = useState<boolean>(false);
  const WrapperContainer = showGreyScaleImage ? Grayscale : View;
  return (
    <SafeAreaView
      style={{
        flex: 1,
        gap: 20,
        backgroundColor: 'white',
        alignItems: 'center',
      }}>
      <View style={{flexDirection: 'row', justifyContent: 'center'}}>
        <TouchableOpacity
          onPress={() => setShowGreyScaleImage(value => !value)}
          style={{backgroundColor: '#DCB3E3', padding: 5, borderRadius: 5}}>
          <Text>Convert to {showGreyScaleImage ? 'Color' : 'Grayscale'}</Text>
        </TouchableOpacity>
      </View>
      <WrapperContainer>
        <Image
          source={{uri: 'https://picsum.photos/200/300'}}
          style={{width: 200, height: 300}}
        />
      </WrapperContainer>
    </SafeAreaView>
  );
}
```

### App Behavior

https://github.com/iyegoroff/react-native-color-matrix-image-filters/assets/4240966/5ca1f626-5219-4983-bdc5-950402b969ac

**Comment by JDWaghela** [comment]
> We are seeing the same issue on iOS version `17.4`
> 
> ### Details
> ```
> platform : iOS
> react-native: 0.71.11
> react-native-color-matrix-image-filters: 6.0.7
> architecture: old
> iosVersion: 17.4 (simulator)
> ```
> 
> ### Code to Reproduce
> ```ts
> import React, {useState} from 'react';
> import {Image, Text, TouchableOpacity, View} from 'react-native';
> import {Grayscale} from 'react-native-color-matrix-image-filters';
> import {SafeAreaView} from 'react-native-safe-area-context';
> 
> export function ReproduceGreyscaleIssue() {
>   const [showGreyScaleImage, setShowGreyScaleImage] = useState<boolean>(false);
>   const WrapperContainer = showGreyScaleImage ? Grayscale : View;
>   return (
>     <SafeAreaView
>       style={{
>         flex: 1,
>         gap: 20,
>         backgroundColor: 'white',
>         alignItems: 'center',
>       }}>
>       <View style={{flexDirection: 'row', justifyContent: 'center'}}>
>         <TouchableOpacity
>           onPress={() => setShowGreyScaleImage(value => !value)}
>           style={{backgroundColor: '#DCB3E3', padding: 5, borderRadius: 5}}>
>           <Text>Convert to {showGreyScaleImage ? 'Color' : 'Grayscale'}</Text>
>         </TouchableOpacity>
>       </View>
>       <WrapperContainer>
>         <Image
>           source={{uri: 'https://picsum.photos/200/300'}}
>           style={{width: 200, height: 300}}
>         />
>       </WrapperContainer>
>     </SafeAreaView>
>   );
> }
> ```
> 
> ### App Behavior
>  Screen.Recording.2024-03-08.at.10.32.17.PM.mov 
> @abs192

Thanks for perfect reproducable steps

**Comment by lifwanian** [comment]
Bump. We're also receiving reports from everyone who upgraded to 17.4.

**Comment by OwenMelbz** [comment]
:D Yes we're also getting this on 17.4

Simple loop usage

```
{ game.summary.home.bans.map(ban => <Grayscale key={ ban.image_url }>
    <Image className="h-8 w-8" source={{ uri: ban.image_url, cache: 'force-cache' }} />
</Grayscale>)}
```

**Comment by RuyVictor** [comment]
The "react-native-fast-image" library has been experiencing many problems in its issues since 2022 that have not yet been resolved, many problems, among them the main one on IOS, some images end up not loading, this was discussed in one of the issues , if possible, prioritize support for @georstat/react-native-image-cache

Basically it is the successor of the "fast image" library

**Comment by OwenMelbz** [comment]
> react

I don't think that is relevant? We're just using the Image component from react-native and having same issue

**Comment by RuyVictor** [comment]
> > The "react-native-fast-image" library has been experiencing many problems in its issues since 2022 that have not yet been resolved, many problems, among them the main one on IOS, some images end up not loading, this was discussed in one of the issues , if possible, prioritize support for @georstat/react-native-image-cache
> 
> > Basically it is the successor of the "fast image" library
> 
> I don't think that is relevant? We're just using the Image component from react-native and having same issue

Yes, I'm having the same problem as you on IOS 17.4, this library is extremely important, as some people shouldn't be held hostage by react native skia to make grayscale effects. What I said earlier is just highlighting that what was done to support the fast image library was a good step, but it is necessary to be premeditated so as not to make mistakes along the way.

**Comment by rakibuli2gether** [comment]
I am also having the same problem. it is crashing for 17.4 only previous versions are ok. Is there any other way to show the grayscale on FastImage ? Any suggestion for any other library for the time being ?

**Comment by serjek** [comment]
Same with RGBA filter. Strangely enough, this reproduces on simulator but works normally on real device with 17.4.

**Comment by OwenMelbz** [comment]
> Same with RGBA filter. Strangely enough, this reproduces on simulator but works normally on real device with 17.4.

It's anything that uses the matrix as far as I can tell, but does seem to only be affecting Simulators

**Comment by serjek** [comment]
> > Same with RGBA filter. Strangely enough, this reproduces on simulator but works normally on real device with 17.4.
> 
> It's anything that uses the matrix as far as I can tell, but does seem to only be affecting Simulators

Well, who know what surprises may come up in 17.5, unless the root cause is identified we are on a very thin ice.

**Comment by zafree** [comment]
I'm now using `ColorMatrix` instead of `Grayscale`.

Step 1: 
```
import {
  ColorMatrix,
  concatColorMatrices,
  saturate,
  duoTone,
} from 'react-native-color-matrix-image-filters';
```

Step 2: Your markup should be like this:
```
<ColorMatrix
  matrix={concatColorMatrices(
    saturate(0),
    duoTone('#FFFFFF', '#000000'),
  )}>
  ...Image
</ColorMatrix>
```

It renders the same as `Grayscale` does. In my iOS 17.4 simulator, it renders the perfect grayscale image. Could someone please try it and let me know if it works on your simulator or real device?

**Comment by rakibuli2gether** [comment]
It does not work @zafree , it crashes

**Comment by isaac-israel-aquant** [comment]
It is the same here

**Comment by Ewilliams90** [comment]
Also experiencing this issue on iOS 17.4 simulator

**Comment by VikalpP** [comment]
[Upvoted 🔼]
Experiencing the same issue. 
Grayscale is crashing on iOS 17.4

**Comment by rlytvynr** [comment]
The same issue

**Comment by zafree** [comment]
> I'm now using `ColorMatrix` instead of `Grayscale`.
> 
> It renders the same as `Grayscale` does. In my iOS 17.4 simulator, it renders the perfect grayscale image. Could someone please try it and let me know if it works on your simulator or real device?
> 
> Step 1:
> 
> ```
> import {
>   ColorMatrix,
>   concatColorMatrices,
>   saturate,
>   duoTone,
> } from 'react-native-color-matrix-image-filters';
> ```
> 
> Step 2: Your markup should be like this:
> 
> ```
> <ColorMatrix
>   matrix={concatColorMatrices(
>     saturate(0),
>     duoTone('#FFFFFF', '#000000'),
>   )}>
>   ...Image
> </ColorMatrix>
> ```

Everyone is experiencing crashes on the iOS 17.4 simulator. However, the code I shared works normally on my simulator and real device with iOS 17.4.

**Comment by Piero87** [comment]
I have the same problem

**Comment by mayhemphone** [comment]
> > I'm now using `ColorMatrix` instead of `Grayscale`.
> > It renders the same as `Grayscale` does. In my iOS 17.4 simulator, it renders the perfect grayscale image. Could someone please try it and let me know if it works on your simulator or real device?
> > Step 1:
> > ```
> > import {
> >   ColorMatrix,
> >   concatColorMatrices,
> >   saturate,
> >   duoTone,
> > } from 'react-native-color-matrix-image-filters';
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Step 2: Your markup should be like this:
> > ```
> > <ColorMatrix
> >   matrix={concatColorMatrices(
> >     saturate(0),
> >     duoTone('#FFFFFF', '#000000'),
> >   )}>
> >   ...Image
> > </ColorMatrix>
> > ```
> 
> Everyone is experiencing crashes on the iOS 17.4 simulator. However, the code I shared works normally on my simulator and real device with iOS 17.4.

Appreciate the example, but it still crashes for me.

**Comment by unav4ila8le** [comment]
We have the same issue

**Comment by yaroslav-n** [comment]
I don't know much about native iOS programming, but it seems to me that this library is using OpenGL context, which was deprecated for a while. 
Changing it to use Metal seems to solve the issue.

I've replaced the old `createContextWithOptions` method in `CMIFColorMatrixImageFilter.mm` with this (Metal used by default when using `contextWithOptions`):
```
+ (CIContext *)createContextWithOptions:(nullable NSDictionary<NSString *, id> *)options
  {
    return [CIContext contextWithOptions:options];
  }
```

**Comment by iyegoroff** [comment]
Fixed in v6.0.9

**Comment by Swikriti0998** [comment]
I tried changing the version to 6.0.9 but this is still crashing for react native expo
iOS version 17.4
"expo": "^50.0.8"
"react-native": "^0.73.4",
